apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  duration: 2160h
  renewBefore: 360h
  commonName: argocd.cluster
  dnsNames:
    - argocd.cluster
  issuerRef:
    name: ingress
    kind: ClusterIssuer
