apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: ingress-ca
  secretName: ingress-ca-tls
  duration: 8760h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer