apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: online-boutique-tls
  namespace: online-boutique
spec:
  secretName: online-boutique-tls
  dnsNames:
    - online-boutique.demo
  issuerRef:
    name: ingress
    kind: ClusterIssuer