apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: online-boutique-gateway
  namespace: online-boutique
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "online-boutique.cluster"
      tls:
        mode: SIMPLE
        certificateRefs:
          - name: online-boutique-cert-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: online-boutique-vs
  namespace: online-boutique
spec:
  gateways:
    - online-boutique-gateway
  hosts:
    - online-boutique.cluster
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend
            port:
              number: 80