apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: online-boutique-demo
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-demo
  namespace: argocd
spec:
  project: online-boutique-demo
  source:
    repoURL: https://github.com/SerhiiMyronets/homelab-talos-kubernetes-terraform.git
    targetRevision: main
    path: 03-gitops/apps/03-demo/online-boutique
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true