apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SerhiiMyronets/homelab-talos-kubernetes-terraform
    targetRevision: HEAD
    path: 03-gitops/applications/ingress
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true