apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-apps
  namespace: argocd
spec:
  project: ingress
  source:
    repoURL: https://github.com/SerhiiMyronets/homelab-talos-kubernetes-terraform.git
    targetRevision: main
    path: 03-gitops/apps/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}