apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-init
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SerhiiMyronets/homelab-talos-kubernetes-terraform
    targetRevision: HEAD
    path: 03-gitops/apps/vault-init
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true