apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: prometheus
data:
  additional-scrape-configs.yaml: |
    - job_name: 'otel-collector-spanmetrics'
      static_configs:
        - targets: ['otel-collector.monitoring.svc.cluster.local:8889']