apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.5.3
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values.yaml

namespace: longhorn-system
