apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: vault-init
          image: hashicorp/vault:1.15.2
          command:
            - /bin/sh
            - -c
            - |
              echo "Initializing Vault..."
              vault operator init -key-shares=1 -key-threshold=1 -format=json > /vault/data/init.json
              VAULT_UNSEAL_KEY=$(cat /vault/data/init.json | jq -r ".unseal_keys_b64[0]")
              vault operator unseal $VAULT_UNSEAL_KEY
              echo "Vault initialized and unsealed."
          env:
            - name: VAULT_ADDR
              value: "https://vault.cluster"
          volumeMounts:
            - name: vault-ca
              mountPath: /etc/vault/tls
              readOnly: true
            - name: vault-data
              mountPath: /vault/data
      volumes:
        - name: vault-ca
          secret:
            secretName: ingress-tls
        - name: vault-data
          emptyDir: {}
