apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: opentelemetry-demo
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.37.1
    releaseName: otel-demo
    namespace: otel-demo
    valuesFile: values.yaml
