# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-demo
resources:
  - namespace.yaml
  - https://github.com/open-telemetry/opentelemetry-demo//kubernetes?ref=main