apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: PLACEHOLDER
      spec:
        template:
          metadata:
            annotations:
              proxy.istio.io/config: |
                {"tracing":{"sampling":100,"custom_tags":{"service":{"literal":{"value":"$(POD_NAMESPACE)"}}}}}