apiVersion: v1
kind: Service
metadata:
  name: image-provider
  labels:
    helm.sh/chart: opentelemetry-demo-0.37.1

    opentelemetry.io/name: image-provider
    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/component: image-provider
    app.kubernetes.io/name: image-provider
    app.kubernetes.io/version: "2.0.2"
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8081
      name: tcp-service
      targetPort: 8081
  selector:

    opentelemetry.io/name: image-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-provider
  labels:
    helm.sh/chart: opentelemetry-demo-0.37.1

    opentelemetry.io/name: image-provider
    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/component: image-provider
    app.kubernetes.io/name: image-provider
    app.kubernetes.io/version: "2.0.2"
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:

      opentelemetry.io/name: image-provider
  template:
    metadata:
      labels:

        opentelemetry.io/name: image-provider
        app.kubernetes.io/instance: otel-demo
        app.kubernetes.io/component: image-provider
        app.kubernetes.io/name: image-provider
    spec:
      serviceAccountName: otel-demo
      containers:
        - name: image-provider
          image: 'ghcr.io/open-telemetry/demo:2.0.2-image-provider'
          imagePullPolicy: IfNotPresent
          ports:

            - containerPort: 8081
              name: service
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: otel-collector.monitoring
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: IMAGE_PROVIDER_PORT
              value: "8081"
            - name: OTEL_COLLECTOR_PORT_GRPC
              value: "4317"
            - name: OTEL_COLLECTOR_HOST
              value: $(OTEL_COLLECTOR_NAME)
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.0.2
          resources:
            limits:
              memory: 50Mi
          volumeMounts:
      volumes: