apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  commonName: argocd.cluster
  dnsNames:
    - argocd.cluster
  issuerRef:
    name: ingress
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 2160h