nameOverride: otel-collector
fullnameOverride: otel-collector
mode: deployment

config:
  connectors:
    spanmetrics: { }
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
  processors:
    batch: {}
  exporters:
    debug: {}
    otlp:
      endpoint: jaeger-collector.monitoring:4317
      tls:
        insecure: true
      otlphttp/prometheus:
        endpoint: http://prometheus.monitoring:9090/api/v1/otlp
        tls:
          insecure: true
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
      metrics:
        receivers: [otlp]
        processors: []
        exporters: [debug]
      logs:
        receivers: [otlp]
        processors: []
        exporters: [debug]