nameOverride: otel-collector
fullnameOverride: otel-collector
mode: deployment
serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: spanmetrics
      interval: 15s
  extraLabels:
    release: kube-prometheus-stack

config:
  connectors:
    spanmetrics: { }
  receivers:
    httpcheck/frontend-proxy:
      targets:
        - endpoint: http://frontend-proxy:8080
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          cors:
            allowed_origins:
              - http://*
              - https://*
          endpoint: ${env:MY_POD_IP}:4318
    redis:
      collection_interval: 10s
      endpoint: valkey-cart:6379
  exporters:
    debug: {}
    otlp:
      endpoint: jaeger-collector.monitoring:4317
      tls:
        insecure: true
    prometheus:
      endpoint: ${env:MY_POD_IP}:8889
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  processors:
    batch: { }
    k8sattributes:
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
      passthrough: false
      pod_association:
        - sources:
            - from: resource_attribute
              name: k8s.pod.ip
        - sources:
            - from: resource_attribute
              name: k8s.pod.uid
        - sources:
            - from: connection
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25
    resource:
      attributes:
        - action: insert
          from_attribute: k8s.pod.uid
          key: service.instance.id
    transform:
      error_mode: ignore
      trace_statements:
        - context: span
          statements:
            - replace_pattern(name, "\\?.*", "")
            - replace_match(name, "GET /api/products/*", "GET /api/products/{productId}")
  service:
    extensions: [health_check]
    pipelines:
      traces:
        exporters: [otlp, debug, spanmetrics]
        processors: [k8sattributes, memory_limiter, resource, transform, batch]
        receivers: [otlp]
      metrics:
        exporters: [prometheus, debug]
        processors: [k8sattributes, memory_limiter, resource, batch]
        receivers: [httpcheck/frontend-proxy, redis, otlp, spanmetrics]
      logs:
        receivers: [otlp]
        processors: []
        exporters: [debug]
ports:
  metrics:
    enabled: false
  spanmetrics:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP

service:
  enabled: true
  type: ClusterIP