nameOverride: otel-collector
fullnameOverride: otel-collector
mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.98.0

configMap:
  create: true
  name: otel-collector-config
  key: relay.yaml

extraArgs:
  - --config=/conf/relay.yaml

configMapMounts:
  - name: otel-collector-config
    mountPath: /conf
    subPath: relay.yaml
    configMap: otel-collector-config

ports:
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
  spanmetrics:
    enabled: true
    containerPort: 8889
    servicePort: 8889

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: spanmetrics
      interval: 15s
  extraLabels:
    release: kube-prometheus-stack

resources:
  limits:
    memory: 300Mi
  requests:
    memory: 150Mi
