nameOverride: otel-collector
fullnameOverride: otel-collector
mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.98.0

config:
  connectors:
    spanmetrics: {}
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
  exporters:
    otlp:
      endpoint: jaeger-collector.monitoring:4317
      tls:
        insecure: true
    prometheus:
      endpoint: "0.0.0.0:8889"
    logging:
      loglevel: debug
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [spanmetrics, otlp, logging]
      metrics:
        receivers: [ spanmetrics ]
        processors: [ batch ]
        exporters: [ prometheus ]

ports:
  metrics:
    enabled: true
    containerPort: 8889
    servicePort: 8889

service:
  enabled: true
  type: ClusterIP

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: metrics
      interval: 15s
  extraLabels:
    release: kube-prometheus-stack