nameOverride: otel-collector
fullnameOverride: otel-collector
mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.98.0

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
  exporters:
    logging:
      loglevel: debug
  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [logging]

ports:
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
  spanmetrics:
    enabled: true
    containerPort: 8889
    servicePort: 8889

service:
  enabled: true
  type: ClusterIP

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: metrics
      interval: 15s
  extraLabels:
    release: kube-prometheus-stack