nameOverride: otel-collector
fullnameOverride: otel-collector
mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.98.0

config:
  connectors:
    spanmetrics: {}
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
  exporters:
    prometheus: {}
    logging:
      loglevel: debug
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [spanmetrics, logging]
      metrics:
        receivers: [ spanmetrics ]
        processors: [ batch ]
        exporters: [ prometheus ]

ports:
  spanmetrics:
    enabled: true
    containerPort: 8889
    servicePort: 8889

service:
  enabled: true
  type: ClusterIP

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: spanmetrics
      interval: 15s
  extraLabels:
    release: kube-prometheus-stack