nameOverride: otel-collector
fullnameOverride: otel-collector
mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.120.0

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
  processors:
    batch: { }
    spanmetrics:
      metrics_exporter: prometheus
  exporters:
    otlp:
      endpoint: jaeger-collector.monitoring:4317
      tls:
        insecure: true
    prometheus:
      endpoint: "0.0.0.0:8889"
    logging:
      loglevel: debug
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch, spanmetrics]
        exporters: [otlp, logging]
      metrics:
        receivers: [ spanmetrics ]
        processors: [ batch ]
        exporters: [ prometheus ]
    telemetry:
      metrics:
        address: "0.0.0.0:8888"

ports:
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
  spanmetrics:
    enabled: true
    containerPort: 8889
    servicePort: 8889

service:
  enabled: true
  type: ClusterIP


serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: spanmetrics
      interval: 15s
    - port: metrics
      interval: 15s
  extraLabels:
    release: kube-prometheus-stack