nameOverride: otel-collector
fullnameOverride: otel-collector
mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.98.0

command:
  - "/otelcontribcol"
args:
  - "--config=/conf/relay.yaml"

extraVolumes:
  - name: otel-collector-config
    configMap:
      name: otel-collector-config

extraVolumeMounts:
  - name: otel-collector-config
    mountPath: /conf
    subPath: relay.yaml

ports:
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
  spanmetrics:
    enabled: true
    containerPort: 8889
    servicePort: 8889

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: metrics
      interval: 15s
    - port: spanmetrics
      interval: 15s
  extraLabels:
    release: kube-prometheus-stack

resources:
  limits:
    memory: 300Mi
  requests:
    memory: 150Mi